name: first-github-action
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello world!'
      - run: pwd
      - run: ls
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'something'
      - uses: mdallasanta/ssh-scp-deploy@v1.0.5
        with:
          local: './'
          remote: '/opt/'
          host: ${{secrets.SSH_HOST}}
          user: root
          key: ${{secrets.SSH_HOST}}
          pre_upload: echo "This will be executed before the upload!"
          post_upload: echo "This will be executed after the upload!"
          ssh_options: -o StrictHostKeyChecking=no
          scp_options: -v

