name: first-github-action
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Start!'
      - uses: mdallasanta/ssh-scp-deploy@{version}
        with:
          local: './'                                                  # Local file path - REQUIRED false - DEFAULT ./
          remote: '~/'                                                 # Remote file path - REQUIRED false - DEFAULT ~/
          host: ${{secrets.SSH_HOST}}                                         # Remote server port - REQUIRED false - DEFAULT 22
          user: root
          key: ${{secrets.SSH_PRIVATE_KEY}}
          pre_upload: echo "This will be executed before the upload!"  # Command to run via ssh before scp upload - REQUIRED false
          post_upload: echo "This will be executed after the upload!"  # Command to run via ssh after scp upload - REQUIRED false
          ssh_options: -o StrictHostKeyChecking=no                     # A set of ssh_option separated by -o - REQUIRED false - DEFAULT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
          scp_options: -v
      - name: Deploy to Docker swarm
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: root@${{secrets.SSH_HOST}}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          copy_stack_file: true
          deploy_path: /opt/
          stack_file_name: docker-compose.yml
          keep_files: 5
          args: my_applicaion
